## Compares two checksum lists generated by 'dias_mets_filelist.py'

import xml.etree.ElementTree as ET
import pathlib
import sys

# checklist_path_A = r"C:\Users\eirlad\OneDrive - Arkivverket\Skrivebord\Python-greier\skript DIAS\sjekksumlister\checksum_list_3aaede1.csv"
# checklist_path_B = r"C:\Users\eirlad\OneDrive - Arkivverket\Skrivebord\Python-greier\skript DIAS\sjekksumlister\checksum_list_86f5930.csv"

checklist_path_A = sys.argv[1]
checklist_path_B = sys.argv[2]

def checklist_compare (checklist_path_A, checklist_path_B):
    
    print(f"Sammenlikner sjekksumliste/mengde A - {checklist_path_A[-11:]} og sjekksumliste/mengde B - {checklist_path_B[-11:]})
    file_list_A = []
    file_list_B = []
    checksum_list_A = []
    checksum_list_B = []

          
    read_file = open(pathlib.Path(checklist_path_A), "r")
    with read_file as f:
        for line in f:
            file_list_A += [(line.split(';'))]
    read_file.close()
    print(f"Lengde på filliste for menge A: {len(file_list_A)})

    for sjekksum in file_list_A:
        checksum_list_A += [sjekksum[1]]
    print(f"Lengde på sjekksumliste for menge A: {len(checksum_list_A)})

          
    read_file = open(pathlib.Path(checklist_path_B), "r")
    with read_file as f:
        for line in f:
            file_list_B += [(line.split(';'))]
    read_file.close()
    print(f"Lengde på filliste for mengde B: {len(file_list_B)})

    for sjekksum in file_list_B:
        checksum_list_B += [sjekksum[1]]
    print(f"Lengde på sjekksumliste for mengde B: {len(checksum_list_B)})


    set_diff_list_AB = list(set(checksum_list_A).difference(checksum_list_B))
    set_diff_list_BA = list(set(checksum_list_B).difference(checksum_list_A))

    set_sym_diff = set(checksum_list_A).symmetric_difference(checksum_list_B)
    set_intersect = set(checksum_list_A).intersection(checksum_list_B)

    print(f"Så mange finnes i mengde A, som ikke finnes i mengde B: {len(set_diff_list_AB)}")
    print(f"Så mange finnes i mengde B, som ikke finnes i mengde A: {len(set_diff_list_BA)}")
    print(f"Så mange finnes i mengde A, som også finnes i mengde B: {len(set_intersect)}")
    print(f"Så mange finnes i kun én av mengdene: {len(set_sym_diff)}")

checklist_compare(checklist_path_A, checklist_path_B)
